# Use the official Node.js image as the base image
FROM node:lts

# Set the working directory inside the container
WORKDIR /app/frontend

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install --legacy-peer-deps

# Copy the rest of the frontend code to the working directory
COPY . .

# Expose the port on which your frontend app will be served
EXPOSE 80

# Start the React app
CMD ["npm", "start"]